# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Coding Journey
email: brennenawana108ny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is meant to document my personal experience of learning how to 
  code with no previous experience..
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://the-widget.github.io" # the base hostname & protocol for your site
twitter_username: BrennenAwana
github_username:  the-widget
timezone: America/New_York
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
